# Generated by Django 3.1.1 on 2020-09-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('brand', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
                ('use', models.CharField(max_length=200)),
                ('hairtype', models.CharField(max_length=30)),
            ],
        ),
    ]
