# Generated by Django 3.1.1 on 2020-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ManyToManyField(related_name='products', to='service.Service'),
        ),
    ]
