# Generated by Django 3.1.1 on 2020-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200911_1122'),
        ('product', '0003_auto_20200911_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='products', to='service.Service'),
        ),
    ]
