# Generated by Django 3.1.1 on 2020-09-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('bio', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
            ],
        ),
    ]
