# Generated by Django 3.1.1 on 2020-09-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=models.CharField(max_length=200),
        ),
    ]
