# Generated by Django 3.1.1 on 2020-09-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=models.CharField(max_length=1000),
        ),
    ]
