# Generated by Django 3.1.1 on 2020-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200911_1122'),
        ('staff', '0005_auto_20200911_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='staffs', to='service.Service'),
        ),
    ]
