# Generated by Django 3.1.1 on 2020-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200910_2357'),
        ('product', '0002_product_service'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='product',
            field=models.ManyToManyField(related_name='services', to='product.Product'),
        ),
        migrations.AddField(
            model_name='service',
            name='staff',
            field=models.ManyToManyField(related_name='services', to='staff.Staff'),
        ),
    ]
