# Generated by Django 3.1.1 on 2020-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200911_1106'),
        ('staff', '0005_auto_20200911_1106'),
        ('service', '0003_auto_20200911_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='services', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='service',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='services', to='staff.Staff'),
        ),
    ]
