import React from 'react'

const Terms = () => {
  return (
    <section>
      <h1>SALON BOOKING TERMS & CONDITIONS</h1>
      <h2>IMPORTANT APPOINTMENT INFORMATION</h2>
      <p>IN ORDER FOR YOU TO HAVE A SAFE APPOINTMENT WITH US, PLEASE FOLLOW THESE GUIDELINES:
      - IF YOU HAVE ANY SYMPTOMS IF COVID-19 PLEASE DO NOT BOOK
      - IF YOU HAVE AN APPOINTMENT AND START TO DISPLAY SYMPTOMS PLEASE CONTACT US TO CANCEL AS SOON AS POSSIBLE
      - ARRIVE WEARING A FACE MASK THAT GOES OVER YOUR EARS AND KEEP THIS ON FOR THE DURATION OF YOUR APPOINTMENT
      - CARD PAYMENTS ONLY
      </p>
      <p>
      YOU CAN BOOK WITH US OVER THE PHONE, ONLINE OR IN PERSON. BOOKING ONLINE IS A REALLY EASY TOOL FOR OUR EXISTING CLIENTS. HOWEVER, IF YOU ARE NEW TO US OR YOUR LAST APPOINTMENT AT BLEACH LONDON WAS MORE THAN 6 MONTHS AGO, WE WILL REQUIRE YOU TO VISIT ONE OF OUR SALONS FOR A CONSULTATION AND ALLERGY TEST AT LEAST 48 HOURS BEFORE AN APPOINTMENT CAN HAPPEN. APPOINTMENTS CANNOT BE BOOKED UNTIL AN ALLERGY TEST HAS BEEN COMPLETED. WE DO CONSULTATIONS ON A WALK-IN BASIS SO JUST POP BY THE SALON YOU WISH TO VISIT FOR A CHAT WITH A STYLIST.
      BOOKINGS MAY NEED TO BE AMENDED SHOULD THEY NOT FIT IN WITH TIMES AVAILABLE FOR THE SERVICE WANTED. WE WILL DO OUR BEST TO CONTACT YOU IF THERE IS ANYTHING THAT NEEDS TO BE AMENDED OR THERE ARE ANY ISSUES WITH YOUR BOOKING.
      </p>
      <p>
      BY BOOKING ONLINE, IN PERSON OR OVER THE PHONE YOU AGREE TO THE FOLLOWING TERMS AND CONDITIONS:
      </p>
      <p>
      1. WE COMPLY WITH ALL MANUFACTURER'S INSTRUCTIONS REGARDING ALLERGY TESTING AND HEALTH AND SAFETY. AN ALLERGY TEST MUST BE CARRIED OUT AT LEAST 48 HOURS BEFORE AN APPOINTMENT. APPOINTMENTS MUST NOT BE BOOKED UNTIL AN ALLERGY TEST HAS BEEN COMPLETED.
      </p>
      <p>
      2. A DEPOSIT OF £55 IS TO BE MADE EITHER ONLINE, IN PERSON OR OVER THE PHONE TO SECURE A BOOKING. IN CASE OF A NO-SHOW OR LATE CANCELLATION THIS IS NON-REFUNDABLE. THE DEPOSIT GOES TOWARDS THE FINAL VALUE OF THE SERVICE.
      </p>
      <p>
      3. WE WILL TEXT OR CALL TO SEEK CONFIRMATION OF YOUR APPOINTMENT 48 HOURS BEFORE THE BOOKING. YOU MUST REPLY TO CONFIRM YOUR BOOKING.
      </p>
      <p>
      4. CANCELLATIONS MUST BE MADE AT LEAST 48 HOURS BEFORE THE APPOINTMENT. IF MADE WITHIN 48 HOURS THE DEPOSIT CANNOT BE REFUNDED. WE RESERVE THE RIGHT TO CANCEL AN APPOINTMENT IF AN ALLERGY TEST HAS NOT BEEN CARRIED OUT AND/OR A DEPOSIT HASN'T BEEN PAID AT THE TIME OF BOOKING. THE DEPOSIT IS NON-REFUNDABLE IF YOU BOOK ONLINE WITHOUT HAVING HAD AN ALLERGY TEST AND THE APPOINTMENT HASN'T BEEN CANCELLED WITHIN 48 HOURS.
      </p>
      <p>
      5. TIME SLOTS ARE ALLOCATED IN ACCORDANCE WITH THE SERVICES REQUIRED. IF YOU ARE MORE THAN 15 MINUTES LATE, YOUR APPOINTMENT MAY HAVE TO BE CANCELLED OR RESCHEDULED SO AS NOT TO DELAY OTHER SERVICES. YOUR DEPOSIT MAY NOT BE REFUNDED
      </p>
      <p>
      6. UNDER 16S WILL NEED TO BE ACCOMPANIED BY A PARENT OR GUARDIAN TO THE CONSULTATION AND APPOINTMENT. COLOUR SERVICES CANNOT BE CARRIED OUT ON THOSE UNDER THE AGE OF 16.
      </p>
      <p>
      8. IN THE EVENT WE NEED TO RESCHEDULE OR CANCEL YOUR APPOINTMENT DUE TO EVENTS OUTSIDE OF THE STYLIST'S OR SALON'S CONTROL WE WILL DO OUR BEST TO FIND THE NEXT AVAILABLE APPOINTMENT AND EITHER HOLD YOUR DEPOSIT TO GO TOWARDS THE APPOINTMENT OR REFUND IT SHOULD YOU WISH TO CANCEL. ONLINE BOOKING DEPOSITS CAN TAKE UP TO 5-10 WORKING DAYS TO BE REFUNDED.
      </p>
      <p>
      9. TONERS AND SUPER COOL COLOURS LAST BETWEEN 1-3 WASHES FOR PASTEL COLOURS AND MUCH LONGER FOR DEEPER COLOURS, SOMETIMES AS LONG AS 6 MONTHS. THE LONGEVITY OF YOUR HAIR COLOUR CAN BE AFFECTED BY OVER WASHING, HEAT, SUNLIGHT, POLLUTION, SWIMMING AND HAIR PRODUCTS AS WELL AS HAIR POROSITY AND HISTORY. YOUR STYLIST CAN ADVISE ON HOW LONG THE COLOUR WILL LAST AND HOW TO MAINTAIN IT.
      </p>
      <p>
      10. YOUR STYLIST WILL ADVISE ABOUT THE PROCESS YOUR HAIR NEEDS TO GO THROUGH TO ACHIEVE YOUR DESIRED COLOUR. A BIG COLOUR CORRECTION CAN BE A PROCESS THAT NEEDS TO BE REPEATED EVERY 6-8 WEEKS TO ACHIEVE THE DESIRED LOOK. MIRACLES CAN HAPPEN BUT PLEASE BE PATIENT AS WE CARE MOST ABOUT THE OVERALL CONDITION OF YOUR HAIR AND YOUR STYLIST WILL NOT CARRY OUT A SERVICE THAT COULD SEVERELY DAMAGE YOUR HAIR.
      </p>
      <p>
      11. IF YOU ARE UNHAPPY WITH ANY PART OF YOUR SERVICE, PLEASE INFORM YOUR STYLIST IMMEDIATELY WHO WILL ENDEAVOUR TO RECTIFY THE SITUATION.
      </p>

    </section>

  )
}

export default Terms
