import React from 'react'

import Footer from '../common/Footer'

const Terms = () => {
  return (
    <section className="productbackground">
      <div className="container">
        <h1 className="termsTitle">SALON BOOKING TERMS & CONDITIONS</h1>
        <h2 className="termsTitle2">IMPORTANT APPOINTMENT INFORMATION</h2>
        <p className="points">IN ORDER FOR YOU TO HAVE A SAFE APPOINTMENT WITH US, PLEASE FOLLOW THESE GUIDELINES:
      - IF YOU HAVE ANY SYMPTOMS IF COVID-19 PLEASE DO NOT BOOK
      - IF YOU HAVE AN APPOINTMENT AND START TO DISPLAY SYMPTOMS PLEASE CONTACT US TO CANCEL AS SOON AS POSSIBLE
      - ARRIVE WEARING A FACE MASK THAT GOES OVER YOUR EARS AND KEEP THIS ON FOR THE DURATION OF YOUR APPOINTMENT
      - CARD PAYMENTS ONLY
        </p>
        <br></br>
        <p className="points">
      YOU CAN BOOK WITH US OVER THE PHONE, ONLINE OR IN PERSON. BOOKING ONLINE IS EASY TO USE FOR OUR EXISTING CLIENTS. HOWEVER, IF YOU ARE NEW TO US OR YOUR LAST APPOINTMENT WAS MORE THAN 6 MONTHS AGO, WE WILL REQUIRE YOU TO VISIT FOR A CONSULTATION AND ALLERGY TEST AT LEAST 48 HOURS BEFORE AN APPOINTMENT CAN HAPPEN.  WE DO CONSULTATIONS ON A WALK-IN BASIS SO JUST POP BY THE SALON YOU WISH TO VISIT FOR A CHAT WITH A STYLIST.
        </p>
        <br></br>
        <p className="points">
      BY BOOKING ONLINE, IN PERSON OR OVER THE PHONE YOU AGREE TO THE FOLLOWING TERMS AND CONDITIONS:
        </p>
        <br></br>
        <p className="points">
      1. WE COMPLY WITH ALL MANUFACTURER'S INSTRUCTIONS REGARDING ALLERGY TESTING AND HEALTH AND SAFETY. AN ALLERGY TEST MUST BE CARRIED OUT AT LEAST 48 HOURS BEFORE AN APPOINTMENT. APPOINTMENTS MUST NOT BE BOOKED UNTIL AN ALLERGY TEST HAS BEEN COMPLETED.
        </p>
        <br></br>
        <p className="points">
      3. WE WILL TEXT CONFIRMATION OF YOUR APPOINTMENT 24 HOURS BEFORE THE BOOKING.
        </p>
        <br></br>
        <p className="points">
      4. CANCELLATIONS MUST BE MADE AT LEAST 24 HOURS BEFORE THE APPOINTMENT.
        </p >
        <br></br>
        <p className="points">
      5. TIME SLOTS ARE ALLOCATED IN ACCORDANCE WITH THE SERVICES REQUIRED. IF YOU ARE MORE THAN 15 MINUTES LATE, YOUR APPOINTMENT MAY HAVE TO BE CANCELLED OR RESCHEDULED SO AS NOT TO DELAY OTHER SERVICES.
        </p>
        <br></br>
        <p className="points">
      6. UNDER 16S WILL NEED TO BE ACCOMPANIED BY A PARENT OR GUARDIAN TO THE CONSULTATION AND APPOINTMENT. COLOUR SERVICES CANNOT BE CARRIED OUT ON THOSE UNDER THE AGE OF 16.
        </p>
        <br></br>
        <p className="points">
      8. IN THE EVENT WE NEED TO RESCHEDULE OR CANCEL YOUR APPOINTMENT DUE TO EVENTS OUTSIDE OF THE STYLIST'S OR SALON'S CONTROL WE WILL DO OUR BEST TO FIND THE NEXT AVAILABLE APPOINTMENT.
        </p>
        <br></br>
        <p className="points">
      9. TONERS AND CRAZY COLOURS LAST BETWEEN 1-3 WASHES FOR PASTEL COLOURS AND MUCH LONGER FOR DEEPER COLOURS. THE LONGEVITY OF YOUR HAIR COLOUR CAN BE AFFECTED BY OVER WASHING, HEAT, SUNLIGHT, POLLUTION, SWIMMING AND HAIR PRODUCTS AS WELL AS HAIR POROSITY AND HISTORY.
        </p>
        <br></br>
        <p className="points">
      10. YOUR STYLIST WILL ADVISE YOU WITH THE PROCESS YOUR HAIR NEEDS TO GO THROUGH TO ACHIEVE YOUR DESIRED COLOUR. A BIG COLOUR CORRECTION CAN BE A PROCESS THAT NEEDS TO BE REPEATED EVERY 6-8 WEEKS TO ACHIEVE THE DESIRED LOOK.
        </p>
        <br></br>
        <p className="points">
      11. IF YOU ARE UNHAPPY WITH ANY PART OF YOUR SERVICE, PLEASE INFORM YOUR STYLIST OR MANAGER IMMEDIATELY AND WE WILL RECTIFY THE SITUATION.
        </p>
        <br></br>
        <Footer />
      </div>
    </section>

  )
}

export default Terms
